/// 言語設定用。
enum AppLanguage { en, jp }

/// 多言語対応のための文字列管理クラス。
class AppLocalizations {
  final AppLanguage language;

  AppLocalizations(this.language);

  static final Map<AppLanguage, Map<String, String>> _strings = {
    AppLanguage.en: {
      'game_standard': 'Standard',
      'game_switch': 'Switch',
      'game_freebet': 'Free Bet',
      'balance': 'BALANCE',
      'current_bet': 'CURRENT BET',
      'dealer': 'DEALER',
      'player': 'PLAYER',
      'hand': 'HAND',
      'hit': 'HIT',
      'stand': 'STAND',
      'double': 'DOUBLE',
      'split': 'SPLIT',
      'surrender': 'SURRENDER',
      'strategy': 'STRATEGY',
      'switch': 'SWITCH',
      'settings': 'Settings',
      'base_bet': 'Base Bet',
      'bet_unit': 'Bet Unit',
      'max_bet': 'Max Bet',
      'betting_strategy': 'Betting Strategy',
      'balance_mgmt': 'Balance Management',
      'set_balance': 'Set Balance',
      'update_reset': 'UPDATE & RESET HISTORY',
      'close': 'CLOSE',
      'soft_hand_mode': 'Soft Hand Mode',
      'soft_hand_desc': 'Prioritize Ace in starting hands',
      'show_total': 'Show Total Score',
      'show_total_desc': 'Display the sum of card values',
      'language': 'Language',
      'accuracy': 'Accuracy',
      'win': 'WIN',
      'loss': 'LOSS',
      'push': 'PUSH',
      'blackjack': 'BLACKJACK',
      'bust': 'BUST',
      'perfect': 'Perfect! Strategy Correct ✅',
      'mistake': 'Mistake! Better Move: ',
      'streak_wins': ' WINS IN A ROW! 🔥',
      'streak_losses': ' LOSSES IN A ROW... ❄️',
      'no_funds': 'Insufficient balance',
      'no_funds_double': 'Insufficient funds for double down',
      'no_funds_split': 'Insufficient funds for split',
      'cant_resplit': 'Cannot re-split',
      'cant_surrender': 'Cannot surrender in Switch mode',
      'switched': 'Switched cards!',
      'next_game': 'NEXT GAME',
      'deal': 'DEAL',
      'statistics': 'Statistics Dashboard',
      'profit': 'PROFIT',
      'strategy_accuracy': 'STRATEGY ACCURACY',
      'profit_loss_trend': 'Profit & Loss Trend',
      'strategy_perf': 'Strategy Performance',
      'accuracy_trend': 'Accuracy Trend (Last 50 Moves)',
      'reset_stats': 'Reset Statistics?',
      'reset_desc': 'All tracking data will be cleared.',
      'cancel': 'CANCEL',
      'reset': 'RESET',
      'menu_practice_title': 'Strategy Practice',
      'menu_practice_sub': 'Master the basic strategy',
      'menu_standard_title': 'Standard Simulation',
      'menu_standard_sub': 'Real-world betting simulator',
      'menu_switch_title': 'Switch Simulation',
      'menu_switch_sub': 'Play two hands and swap',
      'menu_freebet_title': 'Free Bet Simulation',
      'menu_freebet_sub': 'Complimentary double & split',
      'strategy_desc_flat': 'Always bet the same amount. Safest approach.',
      'strategy_desc_martingale': 'Double bet after a loss. High risk, high reward.',
      'strategy_desc_goodman': '1-2-3-5 system. Increase bet on wins, reset on loss.',
      'strategy_desc_fibonacci': 'Follow the Fibonacci sequence (1, 1, 2, 3, 5...). Increase on loss.',
      'strategy_desc_parlay': 'Double bet after a win. Goal is to win big in a short streak.',
      'strategy_desc_dalembert': 'Increase by 1 after a loss, decrease by 1 after a win. Low volatility.',
    },
    AppLanguage.jp: {
      'game_standard': 'スタンダード',
      'game_switch': 'スイッチ',
      'game_freebet': 'フリーベット',
      'balance': '残高',
      'current_bet': '現在のベット',
      'dealer': 'ディーラー',
      'player': 'プレイヤー',
      'hand': 'ハンド',
      'hit': 'ヒット',
      'stand': 'スタンド',
      'double': 'ダブル',
      'split': 'スプリット',
      'surrender': 'サレンダー',
      'strategy': '戦略確認',
      'switch': 'スイッチ',
      'settings': '設定',
      'base_bet': '基本ベット',
      'bet_unit': 'ベット単位',
      'max_bet': '最大ベット',
      'betting_strategy': 'ベット戦略',
      'balance_mgmt': '残高管理',
      'set_balance': '残高設定',
      'update_reset': '更新＆履歴リセット',
      'close': '閉じる',
      'soft_hand_mode': 'ソフトハンド練習',
      'soft_hand_desc': 'Aを含む手札を優先して配ります',
      'show_total': '合計値を表示',
      'show_total_desc': '手札の合計値を表示します',
      'language': '言語',
      'accuracy': '正解率',
      'win': '勝ち',
      'loss': '負け',
      'push': '引き分け',
      'blackjack': 'ブラックジャック',
      'bust': 'バスト',
      'perfect': '完璧！戦略通りです ✅',
      'mistake': 'ミス！推奨アクション: ',
      'streak_wins': ' 連勝中！ 🔥',
      'streak_losses': ' 連敗中... ❄️',
      'no_funds': '残高が不足しています',
      'no_funds_double': 'ダブルダウンの資金が足りません',
      'no_funds_split': 'スプリットの資金が足りません',
      'cant_resplit': '再スプリットはできません',
      'cant_surrender': 'スイッチモードではサレンダーできません',
      'switched': 'カードを交換しました！',
      'next_game': '次のゲーム',
      'deal': 'ディール',
      'statistics': '統計ダッシュボード',
      'profit': '収支',
      'strategy_accuracy': 'ストラテジー正解率',
      'profit_loss_trend': '収支推移',
      'strategy_perf': '手法別パフォーマンス',
      'accuracy_trend': '正解率推移 (直近50手)',
      'reset_stats': '統計をリセットしますか？',
      'reset_desc': 'すべての履歴データが消去されます。',
      'cancel': 'キャンセル',
      'reset': 'リセット',
      'menu_practice_title': 'ストラテジー練習',
      'menu_practice_sub': '基本戦略をマスターする',
      'menu_standard_title': 'スタンダード',
      'menu_standard_sub': '本格的な資金シミュレーション',
      'menu_switch_title': 'スイッチ',
      'menu_switch_sub': '2つの手札を入れ替えて攻略',
      'menu_freebet_title': 'フリーベット',
      'menu_freebet_sub': 'ダブル・スプリットが無料',
      'strategy_desc_flat': '常に一定額を賭ける、最も安全な手法です。',
      'strategy_desc_martingale': '負けたら倍額を賭ける、ハイリスク・ハイリターンの代表格。',
      'strategy_desc_goodman': '1-2-3-5法。勝ったら増やし、負けたらリセットします。',
      'strategy_desc_fibonacci': 'フィボナッチ数列に従って、負けたら賭け金を増やします。',
      'strategy_desc_parlay': '勝ったら倍額を賭ける、逆マーチンゲール法。連勝で利益を狙います。',
      'strategy_desc_dalembert': '負けたら1単位増やし、勝ったら1単位減らす、リスクを抑えた手法。',
    },
  };

  String get(String key) {
    return _strings[language]?[key] ?? key;
  }
}
